spring:
  application:
    name: document-management-system

  datasource:
    url: jdbc:postgresql://postgres:5432/docflowdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Auto-creates/updates schema on startup
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

server:
  port: 8080
  # servlet:
  #   context-path: /api

logging:
  level:
    root: INFO
    "[com.tech.docflow]": DEBUG
    "[org.springframework.security]": DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

file:
  storage:
    type: ${FILE_STORAGE_TYPE:minio}
    local:
      upload-dir: ${FILE_STORAGE_LOCAL_UPLOAD_DIR:./uploads}
    minio:
      endpoint: ${MINIO_ENDPOINT:http://minio:9000}
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
      bucket-name: ${MINIO_BUCKET_NAME}
      region: ${MINIO_REGION}

ocr:
  max-retries: 3
  retry-delay-seconds: 10
  tika:
    enabled: true
  tesseract:
    enabled: true
    data-path: /usr/share/tesseract-ocr/4.00/tessdata